[package]
name = "hello-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ferris-says = "0.3.1"
webdav-handler = {git = "https://github.com/miquels/webdav-handler-rs.git"}
thiserror = "1"
futures = "0.3"
bytes = "1.5"
percent-encoding = "2.3"
mockall = "0.12"